"""Domain layer for the hotel issue resolution system.

This module contains the core business logic, models, interfaces, and exceptions
that are independent of any infrastructure concerns.
"""

# Import all domain models
from .models import (
    Booking,
    Guest,
    Room,
    Issue,
    IssueType,
    IssueChannel,
    IssuePriority,
    Skill,
    SkillStep,
    SkillStatus,
    RetrievedContext,
    RAGContext,
    ApprovalRequest,
    ApprovalToken,
    ApprovalStatus,
    RiskLevel,
    Resolution,
    ResolutionStatus,
)

# Import all domain interfaces
from .interfaces import (
    IRAGRetriever,
    ISkillMatcher,
    SkillMatchResult,
    IToolExecutor,
    ToolExecutionResult,
    ToolExecutionStatus,
    IApprovalGateway,
    IExecutor,
    IOrchestrator,
)

# Import all domain exceptions
from .exceptions import (
    DomainException,
    ValidationError,
    BookingError,
    BookingNotFoundError,
    InvalidBookingStateError,
    BookingConflictError,
    IssueError,
    IssueNotFoundError,
    InvalidIssueStateError,
    SkillError,
    SkillNotFoundError,
    SkillMatchError,
    SkillRegistrationError,
    SkillUpdateError,
    SkillDeletionError,
    SkillRetrievalError,
    SkillIndexError,
    SkillCompilationError,
    SkillExecutionError,
    RAGError,
    RetrievalError,
    IngestionError,
    EmbeddingError,
    RerankingError,
    ChunkingError,
    ToolError,
    ToolNotFoundError,
    ToolExecutionError,
    ToolValidationError,
    ToolRetrievalError,
    UnauthorizedExecutionError,
    ApprovalError,
    ApprovalNotFoundError,
    ApprovalRequestError,
    InvalidApprovalStateError,
    ApprovalRetrievalError,
    TokenNotFoundError,
    TokenRevocationError,
    TokenExpiredError,
    TokenInvalidError,
    ResolutionError,
    ResolutionNotFoundError,
    InvalidResolutionStateError,
    StepNotFoundError,
    ExecutionError,
    CancellationError,
    OrchestrationError,
    ClassificationError,
    ReasoningError,
    GuardrailError,
    PIIDetectedError,
    PromptInjectionError,
    LowConfidenceError,
    RateLimitError,
    NotificationError,
    MetricsError,
    MetricsRetrievalError,
)

__all__ = [
    # Models
    "Booking",
    "Guest",
    "Room",
    "Issue",
    "IssueType",
    "IssueChannel",
    "IssuePriority",
    "Skill",
    "SkillStep",
    "SkillStatus",
    "RetrievedContext",
    "RAGContext",
    "ApprovalRequest",
    "ApprovalToken",
    "ApprovalStatus",
    "RiskLevel",
    "Resolution",
    "ResolutionStatus",
    
    # Interfaces
    "IRAGRetriever",
    "ISkillMatcher",
    "SkillMatchResult",
    "IToolExecutor",
    "ToolExecutionResult",
    "ToolExecutionStatus",
    "IApprovalGateway",
    "IExecutor",
    "IOrchestrator",
    
    # Exceptions
    "DomainException",
    "ValidationError",
    "BookingError",
    "BookingNotFoundError",
    "InvalidBookingStateError",
    "BookingConflictError",
    "IssueError",
    "IssueNotFoundError",
    "InvalidIssueStateError",
    "SkillError",
    "SkillNotFoundError",
    "SkillMatchError",
    "SkillRegistrationError",
    "SkillUpdateError",
    "SkillDeletionError",
    "SkillRetrievalError",
    "SkillIndexError",
    "SkillCompilationError",
    "SkillExecutionError",
    "RAGError",
    "RetrievalError",
    "IngestionError",
    "EmbeddingError",
    "RerankingError",
    "ChunkingError",
    "ToolError",
    "ToolNotFoundError",
    "ToolExecutionError",
    "ToolValidationError",
    "ToolRetrievalError",
    "UnauthorizedExecutionError",
    "ApprovalError",
    "ApprovalNotFoundError",
    "ApprovalRequestError",
    "InvalidApprovalStateError",
    "ApprovalRetrievalError",
    "TokenNotFoundError",
    "TokenRevocationError",
    "TokenExpiredError",
    "TokenInvalidError",
    "ResolutionError",
    "ResolutionNotFoundError",
    "InvalidResolutionStateError",
    "StepNotFoundError",
    "ExecutionError",
    "CancellationError",
    "OrchestrationError",
    "ClassificationError",
    "ReasoningError",
    "GuardrailError",
    "PIIDetectedError",
    "PromptInjectionError",
    "LowConfidenceError",
    "RateLimitError",
    "NotificationError",
    "MetricsError",
    "MetricsRetrievalError",
]
